---
title: "STA442 HW2 Appedix"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Question 1: Math

```{r}
data("MathAchieve",package = "MEMSS")
```


```{r}
library("lme4")
library("nlme")
library("tidyverse")
library("merTools")

MathLme = nlme::lme(MathAch ~ Minority + SES, random = ~ 1|School ,data = MathAchieve)
# Figure 2: Output for Fixed Effect in Mixed Effect Models
knitr::kable(summary(MathLme)$tTable[,-3],digital=3)

# Figure 3: Estimates of Random Effects and their intervals
MathLme2 = lme4::lmer(MathAch ~ Minority + SES +(1|School), data = MathAchieve)
plotREsim(REsim(MathLme2))

# Figure 4: Output for Random Effects in Mixed Effect Model
knitr::kable(VarCorr(MathLme))
```

# Question 2: Drugs
```{r}
library("INLA")
library("Pmisc")

download.file("http://pbrown.ca/teaching/appliedstats/data/drugs.rds", "drugs.rds")
xSub = readRDS("drugs.rds")
forInla = na.omit(xSub)
forInla$y = as.numeric(forInla$completed)
sdires <- sd(forInla$y)

ires = inla(y ~ SUB1 + GENDER + raceEthnicity + homeless 
            + f(STFIPS, hyper=list(prec=list( prior='pc.prec', param=c(3*sdires, 0.01)))) 
            + f(TOWN, hyper=list(prec=list( prior='pc.prec', param=c(3*sdires, 0.01)))),
          data=forInla, family="binomial",
          control.inla = list(strategy='gaussian', int.strategy='eb'))


```

```{r}
summary(ires)

sdState = Pmisc::priorPostSd(ires)
do.call(matplot, sdState$STFIPS$matplot)
do.call(legend, sdState$legend)
```

```{r}
do.call(matplot, sdState$TOWN$matplot)
do.call(legend, sdState$legend)
```

```{r}
# install.packages("data.table", type = "binary")

toPrint = as.data.frame(rbind(exp(ires$summary.fixed[, c(4, 3, 5)]), 
                              sdState$summary[, c(4, 3, 5)]))
sss = "^(raceEthnicity|SUB1|GENDER|homeless|SD)(.[[:digit:]]+.[[:space:]]+| for )?"
toPrint = cbind(variable = gsub(paste0(sss, ".*"),
"\\1", rownames(toPrint)), category = substr(gsub(sss,
"", rownames(toPrint)), 1, 25), toPrint)

Pmisc::mdTable(toPrint, digits = 3, mdToTex = TRUE, 
               guessGroup = TRUE, 
               caption = "Posterior means and quantiles for model parameters.")

ires$summary.random$STFIPS$ID = gsub("[[:punct:]]|[[:digit:]]", "",
                                     ires$summary.random$STFIPS$ID)
ires$summary.random$STFIPS$ID = gsub("DISTRICT OF COLUMBIA", "WASHINGTON DC",
                                     ires$summary.random$STFIPS$ID)
toprint = cbind(ires$summary.random$STFIPS[1:26, c(1, 2, 4, 6)], 
                ires$summary.random$STFIPS[-(1:26), c(1, 2, 4, 6)])
colnames(toprint) = gsub("uant", "", colnames(toprint))
knitr::kable(toprint, digits = 1, format = "latex")
```



